application: trackingzoe
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: (.*)/
  static_files: build\1/index.html
  upload: build/index.html

- url: /
  static_dir: build